<?php

/* 
	------------------------------------------------------------------------	  
	Copyright (C) foBrain Tech LTD (Igweze Ebele Mark) 2010 - 2026.

	Licensed under the Apache License, Version 2.0 (the 'License');
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an 'AS IS' BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License		 
	------------------------------------------------------------------------ 
	foBrain Open Source & wizGrade Open Source App is designed & developed 
	by Igweze Ebele Mark for foBrain Tech LTD

	foBrain School App is Dedicated To Almighty God, My Amazing Parents, 
	To My Fabulous and Supporting Wife Nkiruka J.
	To My Inestimable Kids Osinachi, Ifechukwu, Naetochukwu & Chimamanda.  
	------------------------------------------------------------------------
	WEBSITE 					PHONES/WHATSAPP			EMAILS
	https://www.fobrain.com		+234 - 80 30 716 751  	igweze@fobrain.com	 
	https://www.fobrain.ng		+234 - 80 22 000 490	support@fobrain.com 
	------------------------------------------------------------------------
	
	-------- Script Description --------
	foBrain App Configuration
	------------------------------------------------------------------------*/

	/* DON'T EDIT BELOW UNLESS YOU KNOW WHAT YOU ARE DOING */  

	$FoBrain = 'foBrain AI';    /* App Brand */ 
	$fobrain_version = ' [v3.0]';    /* FoBrain App Version */ 
	 
	$fobrain_demo = 0;  /* 1 means demo mode */  
	$component_free = 0;
	$production_var = 01010104040404012;  /* production or live mode DON'T EDIT */   
    $generatePass = 0;  /* 0 means don't generate passwords while 1 will generate random passwords */ 
 
	$school_list = array (
	
		1=> 'Nursery', 'Primary', 'Secondary' 

	);

	$school_list_2 = array (

		1=> 'Nursery', 'Primary', 'Secondary', 'General'

	);

	$question_list = array (

		1=> 'Option A', 'Option B', 'Option C', 'Option D'

	);

	$question_list_2 = array (

		1=> 'A', 'B', 'C', 'D', 'E'

	);

	$currencySymbols = array(
	
		'AED' => 'United Arab Emirates dirham - د.إ',
		'AFN' => 'Afghan afghani - ؋',
		'ALL' => 'Albanian lek - L',
		'AMD' => 'Armenian dram - դր',
		'AOA' => 'Angolan kwanza - Kz',
		'ARS' => 'Argentine peso - $',
		'AUD' => 'Australian dollar - $',
		'AWG' => 'Aruban florin - ƒ',
		'AZN' => 'Azerbaijani manat - ',
		'BAM' => 'Bosnia and Herzegovina convertible mark - KM',
		'BBD' => 'Barbadian dollar - $',
		'BDT' => 'Bangladeshi taka - ৳',
		'BGN' => 'Bulgarian lev - лв',
		'BHD' => 'Bahraini dinar - .د.ب',
		'BIF' => 'Burundian franc - Fr',
		'BMD' => 'Bermudian dollar - $',
		'BND' => 'Brunei dollar - $',
		'BOB' => 'Bolivian boliviano - Bs',
		'BRL' => 'Brazilian real - R$',
		'BSD' => 'Bahamian dollar - $',
		'BTN' => 'Bhutanese ngultrum - Nu',
		'BWP' => 'Botswana pula - P',
		'BYR' => 'Belarusian ruble - Br',
		'BZD' => 'Belize dollar - $',
		'CAD' => 'Canadian dollar - $',
		'CDF' => 'Congolese franc - Fr',
		'CHF' => 'Swiss franc - Fr',
		'CLP' => 'Chilean peso - $',
		'CNY' => 'Chinese yuan - ¥',
		'COP' => 'Colombian peso - $',
		'CRC' => 'Costa Rican colón - ₡',
		'CUP' => 'Cuban convertible peso - $',
		'CVE' => 'Cape Verdean escudo - $',
		'CZK' => 'Czech koruna - Kč',
		'DJF' => 'Djiboutian franc - Fr',
		'DKK' => 'Danish krone - kr',
		'DOP' => 'Dominican peso - $',
		'DZD' => 'Algerian dinar - د.ج',
		'EGP' => 'Egyptian pound - ج.م',
		'ERN' => 'Eritrean nakfa - Nfk',
		'ETB' => 'Ethiopian birr - Br',
		'EUR' => 'Euro - €',
		'FJD' => 'Fijian dollar - $',
		'FKP' => 'Falkland Islands pound - £',
		'GBP' => 'British pound - £',
		'GEL' => 'Georgian lari - ლ',
		'GHS' => 'Ghana cedi - ₵',
		'GMD' => 'Gambian dalasi - D',
		'GNF' => 'Guinean franc - Fr',
		'GTQ' => 'Guatemalan quetzal - Q',
		'GYD' => 'Guyanese dollar - $',
		'HKD' => 'Hong Kong dollar - $',
		'HNL' => 'Honduran lempira - L',
		'HRK' => 'Croatian kuna - kn',
		'HTG' => 'Haitian gourde - G',
		'HUF' => 'Hungarian forint - Ft',
		'IDR' => 'Indonesian rupiah - Rp',
		'ILS' => 'Israeli new shekel - ₪',
		'IMP' => 'Manx pound - £',
		'INR' => 'Indian rupee - টকা',
		'IQD' => 'Iraqi dinar - ع.د',
		'IRR' => 'Iranian rial - ﷼',
		'ISK' => 'Icelandic króna - kr',
		'JEP' => 'Jersey pound - £',
		'JMD' => 'Jamaican dollar - $',
		'JOD' => 'Jordanian dinar - د.ا',
		'JPY' => 'Japanese yen - ¥',
		'KES' => 'Kenyan shilling - Sh',
		'KGS' => 'Kyrgyzstani som - лв',
		'KHR' => 'Cambodian riel - ៛',
		'KMF' => 'Comorian franc - Fr',
		'KPW' => 'North Korean won - ₩',
		'KRW' => 'South Korean won - ₩',
		'KWD' => 'Kuwaiti dinar - د.ك',
		'KYD' => 'Cayman Islands dollar - $',
		'KZT' => 'Kazakhstani tenge - ₸',
		'LAK' => 'Lao kip - ₭',
		'LBP' => 'Lebanese pound - ل.ل',
		'LKR' => 'Sri Lankan rupee - Rs',
		'LRD' => 'Liberian dollar - $',
		'LSL' => 'Lesotho loti - L',
		'LTL' => 'Lithuanian litas - Lt',
		'LVL' => 'Latvian lats - Ls',
		'LYD' => 'Libyan dinar - ل.د',
		'MAD' => 'Moroccan dirham - د.م.',
		'MDL' => 'Moldovan leu - L',
		'MGA' => 'Malagasy ariary - Ar',
		'MKD' => 'Macedonian denar - ден',
		'MMK' => 'Burmese kyat - Ks',
		'MNT' => 'Mongolian tögrög - ₮',
		'MOP' => 'Macanese pataca - P',
		'MRO' => 'Mauritanian ouguiya - UM',
		'MUR' => 'Mauritian rupee - Rs',
		'MVR' => 'Maldivian rufiyaa - .ރ',
		'MWK' => 'Malawian kwacha - MK',
		'MXN' => 'Mexican peso - $',
		'MYR' => 'Malaysian ringgit - MR',
		'MZN' => 'Mozambican metical - MT',
		'NAD' => 'Namibian dollar - $',
		'NGN' => 'Nigerian naira - ₦',
		'NIO' => 'Nicaraguan córdoba - C$',
		'NOK' => 'Norwegian krone - kr',
		'NPR' => 'Nepalese rupee - Rs',
		'NZD' => 'New Zealand dollar - $',
		'OMR' => 'Omani rial - ر.ع.',
		'PAB' => 'Panamanian balboa - B/.',
		'PEN' => 'Peruvian nuevo sol - S/.',
		'PGK' => 'Papua New Guinean kina - K',
		'PHP' => 'Philippine peso - ₱',
		'PKR' => 'Pakistani rupee - Rs',
		'PLN' => 'Polish złoty - zł',
		'PRB' => 'Transnistrian ruble - р.',
		'PYG' => 'Paraguayan guaraní - ₲',
		'QAR' => 'Qatari riyal - ر.ق',
		'RON' => 'Romanian leu - L',
		'RSD' => 'Serbian dinar - дин',
		'RUB' => 'Russian ruble - руб.',
		'RWF' => 'Rwandan franc - Fr',
		'SAR' => 'Saudi riyal - ر.س',
		'SBD' => 'Solomon Islands dollar - $',
		'SCR' => 'Seychellois rupee - Rs',
		'SDG' => 'Singapore dollar - $',
		'SEK' => 'Swedish krona - kr',
		'SGD' => 'Singapore dollar - $',
		'SHP' => 'Saint Helena pound - £',
		'SLL' => 'Sierra Leonean leone - Le',
		'SOS' => 'Somali shilling - Sh',
		'SRD' => 'Surinamese dollar - $',
		'SSP' => 'South Sudanese pound - £',
		'STD' => 'São Tomé and Príncipe dobra - Db',
		'SVC' => 'Salvadoran colón - ₡',
		'SYP' => 'Syrian pound - £',
		'SZL' => 'Swazi lilangeni - L',
		'THB' => 'Thai baht - ฿',
		'TJS' => 'Tajikistani somoni - SM',
		'TMT' => 'Turkmenistan manat - m',
		'TND' => 'Tunisian dinar - د.ت',
		'TOP' => 'Tongan paʻanga - T$',
		'TRY' => 'Turkish lira - ',
		'TTD' => 'Trinidad and Tobago dollar - $',
		'TWD' => 'New Taiwan dollar - $',
		'TZS' => 'Tanzanian shilling - Sh',
		'UAH' => 'Ukrainian hryvnia - ₴',
		'UGX' => 'Ugandan shilling - Sh',
		'USD' => 'United States dollar - $',
		'UYU' => 'Uruguayan peso - $',
		'UZS' => 'Uzbekistani som - лв',
		'VEF' => 'Venezuelan bolívar - Bs F',
		'VND' => 'Vietnamese đồng - ₫',
		'VUV' => 'Vanuatu vatu - Vt',
		'WST' => 'Samoan tālā - T',
		'XAF' => 'Central African CFA franc - Fr',
		'XCD' => 'East Caribbean dollar - $',
		'XOF' => 'West African CFA franc - Fr',
		'XPF' => 'CFP franc - Fr',
		'YER' => 'Yemeni rial - ﷼',
		'ZAR' => 'South African rand - R',
		'ZMW' => 'Zambian kwacha - ZK',
		'ZWL' => 'Zimbabwean dollar - $'
			
	);							  
			
	$currencySymbolsa = array(
	
		'AED' => '&#1583;.&#1573;', // ?
		'AFN' => '&#65;&#102;',
		'ALL' => '&#76;&#101;&#107;',
		'AMD' => 'դր',
		'ANG' => '&#402;',
		'AOA' => '&#75;&#122;', // ?
		'ARS' => '&#36;',
		'AUD' => '&#36;',
		'AWG' => '&#402;',
		'AZN' => '&#1084;&#1072;&#1085;',
		'BAM' => '&#75;&#77;',
		'BBD' => '&#36;',
		'BDT' => '&#2547;', // ?
		'BGN' => '&#1083;&#1074;',
		'BHD' => '.&#1583;.&#1576;', // ?
		'BIF' => '&#70;&#66;&#117;', // ?
		'BMD' => '&#36;',
		'BND' => '&#36;',
		'BOB' => '&#36;&#98;',
		'BRL' => '&#82;&#36;',
		'BSD' => '&#36;',
		'BTN' => '&#78;&#117;&#46;', // ?
		'BWP' => '&#80;',
		'BYR' => '&#112;&#46;',
		'BZD' => '&#66;&#90;&#36;',
		'CAD' => '&#36;',
		'CDF' => '&#70;&#67;',
		'CHF' => '&#67;&#72;&#70;',
		'CLF' => '', // ?
		'CLP' => '&#36;',
		'CNY' => '&#165;',
		'COP' => '&#36;',
		'CRC' => '&#8353;',
		'CUP' => '&#8396;',
		'CVE' => '&#36;', // ?
		'CZK' => '&#75;&#269;',
		'DJF' => '&#70;&#100;&#106;', // ?
		'DKK' => '&#107;&#114;',
		'DOP' => '&#82;&#68;&#36;',
		'DZD' => '&#1583;&#1580;', // ?
		'EGP' => '&#163;',
		'ETB' => '&#66;&#114;',
		'EUR' => '&#8364;',
		'FJD' => '&#36;',
		'FKP' => '&#163;',
		'GBP' => '&#163;',
		'GEL' => '&#4314;', // ?
		'GHS' => '&#162;',
		'GIP' => '&#163;',
		'GMD' => '&#68;', // ?
		'GNF' => '&#70;&#71;', // ?
		'GTQ' => '&#81;',
		'GYD' => '&#36;',
		'HKD' => '&#36;',
		'HNL' => '&#76;',
		'HRK' => '&#107;&#110;',
		'HTG' => '&#71;', // ?
		'HUF' => '&#70;&#116;',
		'IDR' => '&#82;&#112;',
		'ILS' => '&#8362;',
		'INR' => '&#8377;',
		'IQD' => '&#1593;.&#1583;', // ?
		'IRR' => '&#65020;',
		'ISK' => '&#107;&#114;',
		'JEP' => '&#163;',
		'JMD' => '&#74;&#36;',
		'JOD' => '&#74;&#68;', // ?
		'JPY' => '&#165;',
		'KES' => '&#75;&#83;&#104;', // ?
		'KGS' => '&#1083;&#1074;',
		'KHR' => '&#6107;',
		'KMF' => '&#67;&#70;', // ?
		'KPW' => '&#8361;',
		'KRW' => '&#8361;',
		'KWD' => '&#1583;.&#1603;', // ?
		'KYD' => '&#36;',
		'KZT' => '&#1083;&#1074;',
		'LAK' => '&#8365;',
		'LBP' => '&#163;',
		'LKR' => '&#8360;',
		'LRD' => '&#36;',
		'LSL' => '&#76;', // ?
		'LTL' => '&#76;&#116;',
		'LVL' => '&#76;&#115;',
		'LYD' => '&#1604;.&#1583;', // ?
		'MAD' => '&#1583;.&#1605;.', //?
		'MDL' => '&#76;',
		'MGA' => '&#65;&#114;', // ?
		'MKD' => '&#1076;&#1077;&#1085;',
		'MMK' => '&#75;',
		'MNT' => '&#8366;',
		'MOP' => '&#77;&#79;&#80;&#36;', // ?
		'MRO' => '&#85;&#77;', // ?
		'MUR' => '&#8360;', // ?
		'MVR' => '.&#1923;', // ?
		'MWK' => '&#77;&#75;',
		'MXN' => '&#36;',
		'MYR' => '&#82;&#77;',
		'MZN' => '&#77;&#84;',
		'NAD' => '&#36;',
		'NGN' => '&#8358;',
		'NIO' => '&#67;&#36;',
		'NOK' => '&#107;&#114;',
		'NPR' => '&#8360;',
		'NZD' => '&#36;',
		'OMR' => '&#65020;',
		'PAB' => '&#66;&#47;&#46;',
		'PEN' => '&#83;&#47;&#46;',
		'PGK' => '&#75;', // ?
		'PHP' => '&#8369;',
		'PKR' => '&#8360;',
		'PLN' => '&#122;&#322;',
		'PYG' => '&#71;&#115;',
		'QAR' => '&#65020;',
		'RON' => '&#108;&#101;&#105;',
		'RSD' => '&#1044;&#1080;&#1085;&#46;',
		'RUB' => '&#1088;&#1091;&#1073;',
		'RWF' => '&#1585;.&#1587;',
		'SAR' => '&#65020;',
		'SBD' => '&#36;',
		'SCR' => '&#8360;',
		'SDG' => '&#163;', // ?
		'SEK' => '&#107;&#114;',
		'SGD' => '&#36;',
		'SHP' => '&#163;',
		'SLL' => '&#76;&#101;', // ?
		'SOS' => '&#83;',
		'SRD' => '&#36;',
		'STD' => '&#68;&#98;', // ?
		'SVC' => '&#36;',
		'SYP' => '&#163;',
		'SZL' => '&#76;', // ?
		'THB' => '&#3647;',
		'TJS' => '&#84;&#74;&#83;', // ? TJS (guess)
		'TMT' => '&#109;',
		'TND' => '&#1583;.&#1578;',
		'TOP' => '&#84;&#36;',
		'TRY' => '&#8356;', // New Turkey Lira (old symbol used)
		'TTD' => '&#36;',
		'TWD' => '&#78;&#84;&#36;',
		'TZS' => '',
		'UAH' => '&#8372;',
		'UGX' => '&#85;&#83;&#104;',
		'USD' => '&#36;',
		'UYU' => '&#36;&#85;',
		'UZS' => '&#1083;&#1074;',
		'VEF' => '&#66;&#115;',
		'VND' => '&#8363;',
		'VUV' => '&#86;&#84;',
		'WST' => '&#87;&#83;&#36;',
		'XAF' => '&#70;&#67;&#70;&#65;',
		'XCD' => '&#36;',
		'XDR' => '',
		'XOF' => '',
		'XPF' => '&#70;',
		'YER' => '&#65020;',
		'ZAR' => '&#82;',
		'ZMK' => '&#90;&#75;', // ?
		'ZWL' => '&#90;&#36;'
			
	); 

	$countrylist = array (
	
		1=> "Afghanistan",
		"Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
		"Argentina", "Armenia",  "Australia", "Austria", "Azerbaijan", "Bahamas", 
		"Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin",
		"Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", 
		"Bulgaria", "Burkina Faso", "Burundi",  "Cambodia", "Cameroon", "Canada", 
		"Cape Verde", "Central African Republic", "Chad", "Chile", "China", "Colombia", 
		"Comoros", "Congo", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", 
		"Czech Republic", "Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
		"Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", 
		"Ethiopia", "Fiji", "Finland", "France",  "Gabon", "Gambia", "Georgia", "Germany",
		"Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", 
		"Haiti",  "Honduras", "Hungary",  "Iceland", "India", "Indonesia", "Iran", "Iraq", 
		"Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", 
		"Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", 
		"Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
		"Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", 
		"Marshall Islands", "Mauritania", "Mauritius", "Mexico",  "Micronesia",
		"Moldova", "Monaco", "Mongolia", "Morocco", "Mozambique", "Myanmar", "Namibia", 
		"Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", 
		"North Korea", "Norway", "Oman", "Pakistan", "Palau", "Panama", 
		"Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", 
		"Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", 
		"Saint Vincent and the Grenadines", "Samoa", "San Marino", 
		"Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", 
		"Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", 
		"Somalia", "South Africa", "South Korea", "Spain", "Sri Lanka", "Sudan", 
		"Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan",
		"Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago",
		"Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", 
		"United Arab Emirates", "United Kingdom", "United States", "Uruguay", 
		"Uzbekistan", "Vanuatu", "Vatican", "Venezuela", "Vietnam", "Western Sahara",
		"Yemen", "Zambia", "Zimbabwe"

	);
	
	$educationQuotesArr = array (
		"Education is the adventure that never ends, always leading you to new discoveries.",
		"Through education, we plant the seeds of curiosity that grow into the trees of knowledge.",
		"Learning is the cornerstone of growth; it empowers us to shape our futures with knowledge and confidence.",  
		"Through learning, we gain the tools to build a better world, highlighting the true importance of education in every aspect of life.",
		"Every book read and every lesson learned is a step on the exciting journey of education.",
		"Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime <span> - African Proverb </span>", 
		"Education is the most powerful weapon which you can use to change the world. <span> -  Nelson Mandela </span>", 
		"Education is the magical key that opens the door to a world of possibilities.",
		"The Best way to predict your Future is to create it. <span> - Abraham Lincoln</span>",  
		"Anyone who has never made a mistake has never tried anything new. <span> - Albert Einstein</span>",  
		"An investment in knowledge pays the best interest. <span> - Benjamin Franklin</span>",  
		"Education is what survives when what has been learned has been forgotten. <span> - B.F Skinner</span>",  
		"Never be afraid to try something new.  Remember amateurs built the ark, but professionals built the Titanic. <span> - Unknown</span>",  
		"The beautiful thing about learning is that no one can take it away from you. <span> - B.B King</span>", 
		"The only real failure in life is one not learned from. <span> - Anthony J. D'Angelo</span>",  
		"Education is the bridge that connects dreams to reality.",
		"The importance of education lies in its ability to transform lives; learning opens doors to endless opportunities.",  
		"Education is the key to unlocking the world, a passport to freedom. <span> - Oprah Winfrey</span>",  
		"All of the top achievers I know are life-long learners. Looking for new skills, insights, and ideas. If they're not learning, they're not growing and not moving toward excellence.  <span> - Denis Waitley</span>", 
		"Don't let what you cannot do interfere with what you can do. <span> - John R. Wooden</span>", 
		"Education is not preparation for life; education is life itself. <span> - John Dewey</span>",
		"The roots of education are bitter, but the fruit is sweet. <span> - Aristotle</span>",  
		"Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young. <span> - Henry Ford</span>", 
		"I hear, and I forget.  I see, and I remember. I do, and I understand. <span> - Chinese Proverb</span>", 
		"Education's purpose is to replace an empty mind with an open one. <span> - Malcolm Forbes</span>",  
		"You are always a student, never a master. You have to keep moving forward. <span> - Conrad Hall</span>", 
		"Education is the best friend. An educated person is respected everywhere. Education beats the beauty and the youth. <span> - Chanakya</span>", 
		"Learning is never done without errors and defeat. <span> - Vladimir Lenin</span>", 
		"Education is the ability to listen to almost anything without losing your temper or your self-confidence. Robert Frost <span> - </span>", 
		"Nothing we ever imagined is beyond our powers, only beyond our present self-knowledge <span> - Theodore Roszak</span>",  
		"Teachers open the door, but you must enter by yourself. <span> - Chinese Proverb</span>",  
		"The more that you read, the more things you will know, the more that you learn, the more places you'll go. <span> - Dr. Seuss</span>",  
		"There are two types of people; the can do and the can't.  Which are you? <span> - George R. Cabrera</span>",  
		"They cannot stop me. I will get my education, if it is in the home, school, or anyplace. <span> - Malala Yousafzai</span>",  
		"Who questions much, shall learn much, and retain much. <span> - Francis Bacon</span>", 
		"You haven't failed, until you stop trying <span> - African Proverb </span>", 
		" The only dreams impossible to reach are the ones you never pursue. <span> - Michael Deckman</span>"
	
	);	
							
	

	$translatorArr = array(
	
		'ab' => 'Abkhaz',
		'ace' => 'Acehnese',
		'ach' => 'Acholi',
		'af' => 'Afrikaans',
		'sq' => 'Albanian',
		'alz' => 'Alur',
		'am' => 'Amharic',
		'ar' => 'Arabic',
		'hy' => 'Armenian',
		'as' => 'Assamese',
		'awa' => 'Awadhi',
		'ay' => 'Aymara',
		'az' => 'Azerbaijani',
		'ban' => 'Balinese',
		'bm' => 'Bambara',
		'ba' => 'Bashkir',
		'eu' => 'Basque',
		'btx' => 'Batak Karo',
		'bts' => 'Batak Simalungun',
		'bbc' => 'Batak Toba',
		'be' => 'Belarusian',
		'bem' => 'Bemba',
		'bn' => 'Bengali',
		'bew' => 'Betawi',
		'bho' => 'Bhojpuri',
		'bik' => 'Bikol',
		'bs' => 'Bosnian',
		'br' => 'Breton',
		'bg' => 'Bulgarian',
		'bua' => 'Buryat',
		'yue' => 'Cantonese',
		'ca' => 'Catalan',
		'ceb' => 'Cebuano',
		'ny' => 'Chichewa (Nyanja)',
		'zh-CN' => 'Chinese (Simplified)',
		'zh-TW' => 'Chinese (Traditional)',
		'cv' => 'Chuvash',
		'co' => 'Corsican',
		'crh' => 'Crimean Tatar',
		'hr' => 'Croatian',
		'cs' => 'Czech',
		'da' => 'Danish',
		'din' => 'Dinka',
		'dv' => 'Divehi',
		'doi' => 'Dogri',
		'dov' => 'Dombe',
		'nl' => 'Dutch',
		'dz' => 'Dzongkha',
		'en' => 'English',
		'eo' => 'Esperanto',
		'et' => 'Estonian',
		'ee' => 'Ewe',
		'fj' => 'Fijian',
		'fil' => 'Filipino (Tagalog)',
		'fi' => 'Finnish',
		'fr' => 'French',
		'fr-FR' => 'French (French)',
		'fr-CA' => 'French (Canadian)',
		'fy' => 'Frisian',
		'ff' => 'Fulfulde',
		'gaa' => 'Ga',
		'gl' => 'Galician',
		'lg' => 'Ganda (Luganda)',
		'ka' => 'Georgian',
		'de' => 'German',
		'el' => 'Greek',
		'gn' => 'Guarani',
		'gu' => 'Gujarati',
		'ht' => 'Haitian Creole',
		'cnh' => 'Hakha Chin',
		'ha' => 'Hausa',
		'haw' => 'Hawaiian',
		'he' => 'Hebrew',
		'hil' => 'Hiligaynon',
		'hi' => 'Hindi',
		'hmn' => 'Hmong',
		'hu' => 'Hungarian',
		'hrx' => 'Hunsrik',
		'is' => 'Icelandic',
		'ig' => 'Igbo',
		'ilo' => 'Iloko',
		'id' => 'Indonesian',
		'ga' => 'Irish',
		'it' => 'Italian',
		'ja' => 'Japanese',
		'jw or jv' => 'Javanese',
		'kn' => 'Kannada',
		'pam' => 'Kapampangan',
		'kk' => 'Kazakh',
		'km' => 'Khmer',
		'cgg' => 'Kiga',
		'rw' => 'Kinyarwanda',
		'ktu' => 'Kituba',
		'gom' => 'Konkani',
		'ko' => 'Korean',
		'kri' => 'Krio',
		'ku' => 'Kurdish (Kurmanji)',
		'ckb' => 'Kurdish (Sorani)',
		'ky' => 'Kyrgyz',
		'lo' => 'Lao',
		'ltg' => 'Latgalian',
		'la' => 'Latin',
		'lv' => 'Latvian',
		'lij' => 'Ligurian',
		'li' => 'Limburgan',
		'ln' => 'Lingala',
		'lt' => 'Lithuanian',
		'lmo' => 'Lombard',
		'luo' => 'Luo',
		'lb' => 'Luxembourgish',
		'mk' => 'Macedonian',
		'mai' => 'Maithili',
		'mak' => 'Makassar',
		'mg' => 'Malagasy',
		'ms' => 'Malay',
		'ms-Arab' => 'Malay (Jawi)',
		'ml' => 'Malayalam',
		'mt' => 'Maltese',
		'mi' => 'Maori',
		'mr' => 'Marathi',
		'chm' => 'Meadow Mari',
		'mni-Mtei' => 'Meiteilon (Manipuri)',
		'min' => 'Minang',
		'lus' => 'Mizo',
		'mn' => 'Mongolian',
		'my' => 'Myanmar (Burmese)',
		'nr' => 'Ndebele (South)',
		'new' => 'Nepalbhasa (Newari)',
		'ne' => 'Nepali',
		'nso' => 'Northern Sotho (Sepedi)',
		'no' => 'Norwegian',
		'nus' => 'Nuer',
		'oc' => 'Occitan',
		'or' => 'Odia (Oriya)',
		'om' => 'Oromo',
		'pag' => 'Pangasinan',
		'pap' => 'Papiamento',
		'ps' => 'Pashto',
		'fa' => 'Persian',
		'pl' => 'Polish',
		'pt' => 'Portuguese',
		'pt-PT' => 'Portuguese (Portugal)',
		'pt-BR' => 'Portuguese (Brazil)',
		'pa' => 'Punjabi',
		'pa-Arab' => 'Punjabi (Shahmukhi)',
		'qu' => 'Quechua',
		'rom' => 'Romani',
		'ro' => 'Romanian',
		'rn' => 'Rundi',
		'ru' => 'Russian',
		'sm' => 'Samoan',
		'sg' => 'Sango',
		'sa' => 'Sanskrit',
		'gd' => 'Scots Gaelic',
		'sr' => 'Serbian',
		'st' => 'Sesotho',
		'crs' => 'Seychellois Creole',
		'shn' => 'Shan',
		'sn' => 'Shona',
		'scn' => 'Sicilian',
		'szl' => 'Silesian',
		'sd' => 'Sindhi',
		'si' => 'Sinhala (Sinhalese)',
		'sk' => 'Slovak',
		'sl' => 'Slovenian',
		'so' => 'Somali',
		'es' => 'Spanish',
		'su' => 'Sundanese',
		'sw' => 'Swahili',
		'ss' => 'Swati',
		'sv' => 'Swedish',
		'tg' => 'Tajik',
		'ta' => 'Tamil',
		'tt' => 'Tatar',
		'te' => 'Telugu',
		'tet' => 'Tetum',
		'th' => 'Thai',
		'ti' => 'Tigrinya',
		'ts' => 'Tsonga',
		'tn' => 'Tswana',
		'tr' => 'Turkish',
		'tk' => 'Turkmen',
		'ak' => 'Twi (Akan)',
		'uk' => 'Ukrainian',
		'ur' => 'Urdu',
		'ug' => 'Uyghur',
		'uz' => 'Uzbek',
		'vi' => 'Vietnamese',
		'cy' => 'Welsh',
		'xh' => 'Xhosa',
		'yi' => 'Yiddish',
		'yo' => 'Yoruba',
		'Maya' => 'Yucatec',
		'zu' => 'Zulu'
			
	);

	$timezonesArr = array(

		'America/Adak' => '(GMT-10:00) America/Adak (Hawaii-Aleutian Standard Time)',
		'America/Atka' => '(GMT-10:00) America/Atka (Hawaii-Aleutian Standard Time)',
		'America/Anchorage' => '(GMT-9:00) America/Anchorage (Alaska Standard Time)',
		'America/Juneau' => '(GMT-9:00) America/Juneau (Alaska Standard Time)',
		'America/Nome' => '(GMT-9:00) America/Nome (Alaska Standard Time)',
		'America/Yakutat' => '(GMT-9:00) America/Yakutat (Alaska Standard Time)',
		'America/Dawson' => '(GMT-8:00) America/Dawson (Pacific Standard Time)',
		'America/Ensenada' => '(GMT-8:00) America/Ensenada (Pacific Standard Time)',
		'America/Los_Angeles' => '(GMT-8:00) America/Los_Angeles (Pacific Standard Time)',
		'America/Tijuana' => '(GMT-8:00) America/Tijuana (Pacific Standard Time)',
		'America/Vancouver' => '(GMT-8:00) America/Vancouver (Pacific Standard Time)',
		'America/Whitehorse' => '(GMT-8:00) America/Whitehorse (Pacific Standard Time)',
		'Canada/Pacific' => '(GMT-8:00) Canada/Pacific (Pacific Standard Time)',
		'Canada/Yukon' => '(GMT-8:00) Canada/Yukon (Pacific Standard Time)',
		'Mexico/BajaNorte' => '(GMT-8:00) Mexico/BajaNorte (Pacific Standard Time)',
		'America/Boise' => '(GMT-7:00) America/Boise (Mountain Standard Time)',
		'America/Cambridge_Bay' => '(GMT-7:00) America/Cambridge_Bay (Mountain Standard Time)',
		'America/Chihuahua' => '(GMT-7:00) America/Chihuahua (Mountain Standard Time)',
		'America/Dawson_Creek' => '(GMT-7:00) America/Dawson_Creek (Mountain Standard Time)',
		'America/Denver' => '(GMT-7:00) America/Denver (Mountain Standard Time)',
		'America/Edmonton' => '(GMT-7:00) America/Edmonton (Mountain Standard Time)',
		'America/Hermosillo' => '(GMT-7:00) America/Hermosillo (Mountain Standard Time)',
		'America/Inuvik' => '(GMT-7:00) America/Inuvik (Mountain Standard Time)',
		'America/Mazatlan' => '(GMT-7:00) America/Mazatlan (Mountain Standard Time)',
		'America/Phoenix' => '(GMT-7:00) America/Phoenix (Mountain Standard Time)',
		'America/Shiprock' => '(GMT-7:00) America/Shiprock (Mountain Standard Time)',
		'America/Yellowknife' => '(GMT-7:00) America/Yellowknife (Mountain Standard Time)',
		'Canada/Mountain' => '(GMT-7:00) Canada/Mountain (Mountain Standard Time)',
		'Mexico/BajaSur' => '(GMT-7:00) Mexico/BajaSur (Mountain Standard Time)',
		'America/Belize' => '(GMT-6:00) America/Belize (Central Standard Time)',
		'America/Cancun' => '(GMT-6:00) America/Cancun (Central Standard Time)',
		'America/Chicago' => '(GMT-6:00) America/Chicago (Central Standard Time)',
		'America/Costa_Rica' => '(GMT-6:00) America/Costa_Rica (Central Standard Time)',
		'America/El_Salvador' => '(GMT-6:00) America/El_Salvador (Central Standard Time)',
		'America/Guatemala' => '(GMT-6:00) America/Guatemala (Central Standard Time)',
		'America/Knox_IN' => '(GMT-6:00) America/Knox_IN (Central Standard Time)',
		'America/Managua' => '(GMT-6:00) America/Managua (Central Standard Time)',
		'America/Menominee' => '(GMT-6:00) America/Menominee (Central Standard Time)',
		'America/Merida' => '(GMT-6:00) America/Merida (Central Standard Time)',
		'America/Mexico_City' => '(GMT-6:00) America/Mexico_City (Central Standard Time)',
		'America/Monterrey' => '(GMT-6:00) America/Monterrey (Central Standard Time)',
		'America/Rainy_River' => '(GMT-6:00) America/Rainy_River (Central Standard Time)',
		'America/Rankin_Inlet' => '(GMT-6:00) America/Rankin_Inlet (Central Standard Time)',
		'America/Regina' => '(GMT-6:00) America/Regina (Central Standard Time)',
		'America/Swift_Current' => '(GMT-6:00) America/Swift_Current (Central Standard Time)',
		'America/Tegucigalpa' => '(GMT-6:00) America/Tegucigalpa (Central Standard Time)',
		'America/Winnipeg' => '(GMT-6:00) America/Winnipeg (Central Standard Time)',
		'Canada/Central' => '(GMT-6:00) Canada/Central (Central Standard Time)',
		'Canada/East-Saskatchewan' => '(GMT-6:00) Canada/East-Saskatchewan (Central Standard Time)',
		'Canada/Saskatchewan' => '(GMT-6:00) Canada/Saskatchewan (Central Standard Time)',
		'Chile/EasterIsland' => '(GMT-6:00) Chile/EasterIsland (Easter Is. Time)',
		'Mexico/General' => '(GMT-6:00) Mexico/General (Central Standard Time)',
		'America/Atikokan' => '(GMT-5:00) America/Atikokan (Eastern Standard Time)',
		'America/Bogota' => '(GMT-5:00) America/Bogota (Colombia Time)',
		'America/Cayman' => '(GMT-5:00) America/Cayman (Eastern Standard Time)',
		'America/Coral_Harbour' => '(GMT-5:00) America/Coral_Harbour (Eastern Standard Time)',
		'America/Detroit' => '(GMT-5:00) America/Detroit (Eastern Standard Time)',
		'America/Fort_Wayne' => '(GMT-5:00) America/Fort_Wayne (Eastern Standard Time)',
		'America/Grand_Turk' => '(GMT-5:00) America/Grand_Turk (Eastern Standard Time)',
		'America/Guayaquil' => '(GMT-5:00) America/Guayaquil (Ecuador Time)',
		'America/Havana' => '(GMT-5:00) America/Havana (Cuba Standard Time)',
		'America/Indianapolis' => '(GMT-5:00) America/Indianapolis (Eastern Standard Time)',
		'America/Iqaluit' => '(GMT-5:00) America/Iqaluit (Eastern Standard Time)',
		'America/Jamaica' => '(GMT-5:00) America/Jamaica (Eastern Standard Time)',
		'America/Lima' => '(GMT-5:00) America/Lima (Peru Time)',
		'America/Louisville' => '(GMT-5:00) America/Louisville (Eastern Standard Time)',
		'America/Montreal' => '(GMT-5:00) America/Montreal (Eastern Standard Time)',
		'America/Nassau' => '(GMT-5:00) America/Nassau (Eastern Standard Time)',
		'America/New_York' => '(GMT-5:00) America/New_York (Eastern Standard Time)',
		'America/Nipigon' => '(GMT-5:00) America/Nipigon (Eastern Standard Time)',
		'America/Panama' => '(GMT-5:00) America/Panama (Eastern Standard Time)',
		'America/Pangnirtung' => '(GMT-5:00) America/Pangnirtung (Eastern Standard Time)',
		'America/Port-au-Prince' => '(GMT-5:00) America/Port-au-Prince (Eastern Standard Time)',
		'America/Resolute' => '(GMT-5:00) America/Resolute (Eastern Standard Time)',
		'America/Thunder_Bay' => '(GMT-5:00) America/Thunder_Bay (Eastern Standard Time)',
		'America/Toronto' => '(GMT-5:00) America/Toronto (Eastern Standard Time)',
		'Canada/Eastern' => '(GMT-5:00) Canada/Eastern (Eastern Standard Time)',
		'America/Caracas' => '(GMT-4:-30) America/Caracas (Venezuela Time)',
		'America/Anguilla' => '(GMT-4:00) America/Anguilla (Atlantic Standard Time)',
		'America/Antigua' => '(GMT-4:00) America/Antigua (Atlantic Standard Time)',
		'America/Aruba' => '(GMT-4:00) America/Aruba (Atlantic Standard Time)',
		'America/Asuncion' => '(GMT-4:00) America/Asuncion (Paraguay Time)',
		'America/Barbados' => '(GMT-4:00) America/Barbados (Atlantic Standard Time)',
		'America/Blanc-Sablon' => '(GMT-4:00) America/Blanc-Sablon (Atlantic Standard Time)',
		'America/Boa_Vista' => '(GMT-4:00) America/Boa_Vista (Amazon Time)',
		'America/Campo_Grande' => '(GMT-4:00) America/Campo_Grande (Amazon Time)',
		'America/Cuiaba' => '(GMT-4:00) America/Cuiaba (Amazon Time)',
		'America/Curacao' => '(GMT-4:00) America/Curacao (Atlantic Standard Time)',
		'America/Dominica' => '(GMT-4:00) America/Dominica (Atlantic Standard Time)',
		'America/Eirunepe' => '(GMT-4:00) America/Eirunepe (Amazon Time)',
		'America/Glace_Bay' => '(GMT-4:00) America/Glace_Bay (Atlantic Standard Time)',
		'America/Goose_Bay' => '(GMT-4:00) America/Goose_Bay (Atlantic Standard Time)',
		'America/Grenada' => '(GMT-4:00) America/Grenada (Atlantic Standard Time)',
		'America/Guadeloupe' => '(GMT-4:00) America/Guadeloupe (Atlantic Standard Time)',
		'America/Guyana' => '(GMT-4:00) America/Guyana (Guyana Time)',
		'America/Halifax' => '(GMT-4:00) America/Halifax (Atlantic Standard Time)',
		'America/La_Paz' => '(GMT-4:00) America/La_Paz (Bolivia Time)',
		'America/Manaus' => '(GMT-4:00) America/Manaus (Amazon Time)',
		'America/Marigot' => '(GMT-4:00) America/Marigot (Atlantic Standard Time)',
		'America/Martinique' => '(GMT-4:00) America/Martinique (Atlantic Standard Time)',
		'America/Moncton' => '(GMT-4:00) America/Moncton (Atlantic Standard Time)',
		'America/Montserrat' => '(GMT-4:00) America/Montserrat (Atlantic Standard Time)',
		'America/Port_of_Spain' => '(GMT-4:00) America/Port_of_Spain (Atlantic Standard Time)',
		'America/Porto_Acre' => '(GMT-4:00) America/Porto_Acre (Amazon Time)',
		'America/Porto_Velho' => '(GMT-4:00) America/Porto_Velho (Amazon Time)',
		'America/Puerto_Rico' => '(GMT-4:00) America/Puerto_Rico (Atlantic Standard Time)',
		'America/Rio_Branco' => '(GMT-4:00) America/Rio_Branco (Amazon Time)',
		'America/Santiago' => '(GMT-4:00) America/Santiago (Chile Time)',
		'America/Santo_Domingo' => '(GMT-4:00) America/Santo_Domingo (Atlantic Standard Time)',
		'America/St_Barthelemy' => '(GMT-4:00) America/St_Barthelemy (Atlantic Standard Time)',
		'America/St_Kitts' => '(GMT-4:00) America/St_Kitts (Atlantic Standard Time)',
		'America/St_Lucia' => '(GMT-4:00) America/St_Lucia (Atlantic Standard Time)',
		'America/St_Thomas' => '(GMT-4:00) America/St_Thomas (Atlantic Standard Time)',
		'America/St_Vincent' => '(GMT-4:00) America/St_Vincent (Atlantic Standard Time)',
		'America/Thule' => '(GMT-4:00) America/Thule (Atlantic Standard Time)',
		'America/Tortola' => '(GMT-4:00) America/Tortola (Atlantic Standard Time)',
		'America/Virgin' => '(GMT-4:00) America/Virgin (Atlantic Standard Time)',
		'Antarctica/Palmer' => '(GMT-4:00) Antarctica/Palmer (Chile Time)',
		'Atlantic/Bermuda' => '(GMT-4:00) Atlantic/Bermuda (Atlantic Standard Time)',
		'Atlantic/Stanley' => '(GMT-4:00) Atlantic/Stanley (Falkland Is. Time)',
		'Brazil/Acre' => '(GMT-4:00) Brazil/Acre (Amazon Time)',
		'Brazil/West' => '(GMT-4:00) Brazil/West (Amazon Time)',
		'Canada/Atlantic' => '(GMT-4:00) Canada/Atlantic (Atlantic Standard Time)',
		'Chile/Continental' => '(GMT-4:00) Chile/Continental (Chile Time)',
		'America/St_Johns' => '(GMT-3:-30) America/St_Johns (Newfoundland Standard Time)',
		'Canada/Newfoundland' => '(GMT-3:-30) Canada/Newfoundland (Newfoundland Standard Time)',
		'America/Araguaina' => '(GMT-3:00) America/Araguaina (Brasilia Time)',
		'America/Bahia' => '(GMT-3:00) America/Bahia (Brasilia Time)',
		'America/Belem' => '(GMT-3:00) America/Belem (Brasilia Time)',
		'America/Buenos_Aires' => '(GMT-3:00) America/Buenos_Aires (Argentine Time)',
		'America/Catamarca' => '(GMT-3:00) America/Catamarca (Argentine Time)',
		'America/Cayenne' => '(GMT-3:00) America/Cayenne (French Guiana Time)',
		'America/Cordoba' => '(GMT-3:00) America/Cordoba (Argentine Time)',
		'America/Fortaleza' => '(GMT-3:00) America/Fortaleza (Brasilia Time)',
		'America/Godthab' => '(GMT-3:00) America/Godthab (Western Greenland Time)',
		'America/Jujuy' => '(GMT-3:00) America/Jujuy (Argentine Time)',
		'America/Maceio' => '(GMT-3:00) America/Maceio (Brasilia Time)',
		'America/Mendoza' => '(GMT-3:00) America/Mendoza (Argentine Time)',
		'America/Miquelon' => '(GMT-3:00) America/Miquelon (Pierre & Miquelon Standard Time)',
		'America/Montevideo' => '(GMT-3:00) America/Montevideo (Uruguay Time)',
		'America/Paramaribo' => '(GMT-3:00) America/Paramaribo (Suriname Time)',
		'America/Recife' => '(GMT-3:00) America/Recife (Brasilia Time)',
		'America/Rosario' => '(GMT-3:00) America/Rosario (Argentine Time)',
		'America/Santarem' => '(GMT-3:00) America/Santarem (Brasilia Time)',
		'America/Sao_Paulo' => '(GMT-3:00) America/Sao_Paulo (Brasilia Time)',
		'Antarctica/Rothera' => '(GMT-3:00) Antarctica/Rothera (Rothera Time)',
		'Brazil/East' => '(GMT-3:00) Brazil/East (Brasilia Time)',
		'America/Noronha' => '(GMT-2:00) America/Noronha (Fernando de Noronha Time)',
		'Atlantic/South_Georgia' => '(GMT-2:00) Atlantic/South_Georgia (South Georgia Standard Time)',
		'Brazil/DeNoronha' => '(GMT-2:00) Brazil/DeNoronha (Fernando de Noronha Time)',
		'America/Scoresbysund' => '(GMT-1:00) America/Scoresbysund (Eastern Greenland Time)',
		'Atlantic/Azores' => '(GMT-1:00) Atlantic/Azores (Azores Time)',
		'Atlantic/Cape_Verde' => '(GMT-1:00) Atlantic/Cape_Verde (Cape Verde Time)',
		'Africa/Abidjan' => '(GMT+0:00) Africa/Abidjan (Greenwich Mean Time)',
		'Africa/Accra' => '(GMT+0:00) Africa/Accra (Ghana Mean Time)',
		'Africa/Bamako' => '(GMT+0:00) Africa/Bamako (Greenwich Mean Time)',
		'Africa/Banjul' => '(GMT+0:00) Africa/Banjul (Greenwich Mean Time)',
		'Africa/Bissau' => '(GMT+0:00) Africa/Bissau (Greenwich Mean Time)',
		'Africa/Casablanca' => '(GMT+0:00) Africa/Casablanca (Western European Time)',
		'Africa/Conakry' => '(GMT+0:00) Africa/Conakry (Greenwich Mean Time)',
		'Africa/Dakar' => '(GMT+0:00) Africa/Dakar (Greenwich Mean Time)',
		'Africa/El_Aaiun' => '(GMT+0:00) Africa/El_Aaiun (Western European Time)',
		'Africa/Freetown' => '(GMT+0:00) Africa/Freetown (Greenwich Mean Time)',
		'Africa/Lome' => '(GMT+0:00) Africa/Lome (Greenwich Mean Time)',
		'Africa/Monrovia' => '(GMT+0:00) Africa/Monrovia (Greenwich Mean Time)',
		'Africa/Nouakchott' => '(GMT+0:00) Africa/Nouakchott (Greenwich Mean Time)',
		'Africa/Ouagadougou' => '(GMT+0:00) Africa/Ouagadougou (Greenwich Mean Time)',
		'Africa/Sao_Tome' => '(GMT+0:00) Africa/Sao_Tome (Greenwich Mean Time)',
		'Africa/Timbuktu' => '(GMT+0:00) Africa/Timbuktu (Greenwich Mean Time)',
		'America/Danmarkshavn' => '(GMT+0:00) America/Danmarkshavn (Greenwich Mean Time)',
		'Atlantic/Canary' => '(GMT+0:00) Atlantic/Canary (Western European Time)',
		'Atlantic/Faeroe' => '(GMT+0:00) Atlantic/Faeroe (Western European Time)',
		'Atlantic/Faroe' => '(GMT+0:00) Atlantic/Faroe (Western European Time)',
		'Atlantic/Madeira' => '(GMT+0:00) Atlantic/Madeira (Western European Time)',
		'Atlantic/Reykjavik' => '(GMT+0:00) Atlantic/Reykjavik (Greenwich Mean Time)',
		'Atlantic/St_Helena' => '(GMT+0:00) Atlantic/St_Helena (Greenwich Mean Time)',
		'Europe/Belfast' => '(GMT+0:00) Europe/Belfast (Greenwich Mean Time)',
		'Europe/Dublin' => '(GMT+0:00) Europe/Dublin (Greenwich Mean Time)',
		'Europe/Guernsey' => '(GMT+0:00) Europe/Guernsey (Greenwich Mean Time)',
		'Europe/Isle_of_Man' => '(GMT+0:00) Europe/Isle_of_Man (Greenwich Mean Time)',
		'Europe/Jersey' => '(GMT+0:00) Europe/Jersey (Greenwich Mean Time)',
		'Europe/Lisbon' => '(GMT+0:00) Europe/Lisbon (Western European Time)',
		'Europe/London' => '(GMT+0:00) Europe/London (Greenwich Mean Time)',
		'Africa/Algiers' => '(GMT+1:00) Africa/Algiers (Central European Time)',
		'Africa/Bangui' => '(GMT+1:00) Africa/Bangui (Western African Time)',
		'Africa/Brazzaville' => '(GMT+1:00) Africa/Brazzaville (Western African Time)',
		'Africa/Ceuta' => '(GMT+1:00) Africa/Ceuta (Central European Time)',
		'Africa/Douala' => '(GMT+1:00) Africa/Douala (Western African Time)',
		'Africa/Kinshasa' => '(GMT+1:00) Africa/Kinshasa (Western African Time)',
		'Africa/Lagos' => '(GMT+1:00) Africa/Lagos (Western African Time)',
		'Africa/Libreville' => '(GMT+1:00) Africa/Libreville (Western African Time)',
		'Africa/Luanda' => '(GMT+1:00) Africa/Luanda (Western African Time)',
		'Africa/Malabo' => '(GMT+1:00) Africa/Malabo (Western African Time)',
		'Africa/Ndjamena' => '(GMT+1:00) Africa/Ndjamena (Western African Time)',
		'Africa/Niamey' => '(GMT+1:00) Africa/Niamey (Western African Time)',
		'Africa/Porto-Novo' => '(GMT+1:00) Africa/Porto-Novo (Western African Time)',
		'Africa/Tunis' => '(GMT+1:00) Africa/Tunis (Central European Time)',
		'Africa/Windhoek' => '(GMT+1:00) Africa/Windhoek (Western African Time)',
		'Arctic/Longyearbyen' => '(GMT+1:00) Arctic/Longyearbyen (Central European Time)',
		'Atlantic/Jan_Mayen' => '(GMT+1:00) Atlantic/Jan_Mayen (Central European Time)',
		'Europe/Amsterdam' => '(GMT+1:00) Europe/Amsterdam (Central European Time)',
		'Europe/Andorra' => '(GMT+1:00) Europe/Andorra (Central European Time)',
		'Europe/Belgrade' => '(GMT+1:00) Europe/Belgrade (Central European Time)',
		'Europe/Berlin' => '(GMT+1:00) Europe/Berlin (Central European Time)',
		'Europe/Bratislava' => '(GMT+1:00) Europe/Bratislava (Central European Time)',
		'Europe/Brussels' => '(GMT+1:00) Europe/Brussels (Central European Time)',
		'Europe/Budapest' => '(GMT+1:00) Europe/Budapest (Central European Time)',
		'Europe/Copenhagen' => '(GMT+1:00) Europe/Copenhagen (Central European Time)',
		'Europe/Gibraltar' => '(GMT+1:00) Europe/Gibraltar (Central European Time)',
		'Europe/Ljubljana' => '(GMT+1:00) Europe/Ljubljana (Central European Time)',
		'Europe/Luxembourg' => '(GMT+1:00) Europe/Luxembourg (Central European Time)',
		'Europe/Madrid' => '(GMT+1:00) Europe/Madrid (Central European Time)',
		'Europe/Malta' => '(GMT+1:00) Europe/Malta (Central European Time)',
		'Europe/Monaco' => '(GMT+1:00) Europe/Monaco (Central European Time)',
		'Europe/Oslo' => '(GMT+1:00) Europe/Oslo (Central European Time)',
		'Europe/Paris' => '(GMT+1:00) Europe/Paris (Central European Time)',
		'Europe/Podgorica' => '(GMT+1:00) Europe/Podgorica (Central European Time)',
		'Europe/Prague' => '(GMT+1:00) Europe/Prague (Central European Time)',
		'Europe/Rome' => '(GMT+1:00) Europe/Rome (Central European Time)',
		'Europe/San_Marino' => '(GMT+1:00) Europe/San_Marino (Central European Time)',
		'Europe/Sarajevo' => '(GMT+1:00) Europe/Sarajevo (Central European Time)',
		'Europe/Skopje' => '(GMT+1:00) Europe/Skopje (Central European Time)',
		'Europe/Stockholm' => '(GMT+1:00) Europe/Stockholm (Central European Time)',
		'Europe/Tirane' => '(GMT+1:00) Europe/Tirane (Central European Time)',
		'Europe/Vaduz' => '(GMT+1:00) Europe/Vaduz (Central European Time)',
		'Europe/Vatican' => '(GMT+1:00) Europe/Vatican (Central European Time)',
		'Europe/Vienna' => '(GMT+1:00) Europe/Vienna (Central European Time)',
		'Europe/Warsaw' => '(GMT+1:00) Europe/Warsaw (Central European Time)',
		'Europe/Zagreb' => '(GMT+1:00) Europe/Zagreb (Central European Time)',
		'Europe/Zurich' => '(GMT+1:00) Europe/Zurich (Central European Time)',
		'Africa/Blantyre' => '(GMT+2:00) Africa/Blantyre (Central African Time)',
		'Africa/Bujumbura' => '(GMT+2:00) Africa/Bujumbura (Central African Time)',
		'Africa/Cairo' => '(GMT+2:00) Africa/Cairo (Eastern European Time)',
		'Africa/Gaborone' => '(GMT+2:00) Africa/Gaborone (Central African Time)',
		'Africa/Harare' => '(GMT+2:00) Africa/Harare (Central African Time)',
		'Africa/Johannesburg' => '(GMT+2:00) Africa/Johannesburg (South Africa Standard Time)',
		'Africa/Kigali' => '(GMT+2:00) Africa/Kigali (Central African Time)',
		'Africa/Lubumbashi' => '(GMT+2:00) Africa/Lubumbashi (Central African Time)',
		'Africa/Lusaka' => '(GMT+2:00) Africa/Lusaka (Central African Time)',
		'Africa/Maputo' => '(GMT+2:00) Africa/Maputo (Central African Time)',
		'Africa/Maseru' => '(GMT+2:00) Africa/Maseru (South Africa Standard Time)',
		'Africa/Mbabane' => '(GMT+2:00) Africa/Mbabane (South Africa Standard Time)',
		'Africa/Tripoli' => '(GMT+2:00) Africa/Tripoli (Eastern European Time)',
		'Asia/Amman' => '(GMT+2:00) Asia/Amman (Eastern European Time)',
		'Asia/Beirut' => '(GMT+2:00) Asia/Beirut (Eastern European Time)',
		'Asia/Damascus' => '(GMT+2:00) Asia/Damascus (Eastern European Time)',
		'Asia/Gaza' => '(GMT+2:00) Asia/Gaza (Eastern European Time)',
		'Asia/Istanbul' => '(GMT+2:00) Asia/Istanbul (Eastern European Time)',
		'Asia/Jerusalem' => '(GMT+2:00) Asia/Jerusalem (Israel Standard Time)',
		'Asia/Nicosia' => '(GMT+2:00) Asia/Nicosia (Eastern European Time)',
		'Asia/Tel_Aviv' => '(GMT+2:00) Asia/Tel_Aviv (Israel Standard Time)',
		'Europe/Athens' => '(GMT+2:00) Europe/Athens (Eastern European Time)',
		'Europe/Bucharest' => '(GMT+2:00) Europe/Bucharest (Eastern European Time)',
		'Europe/Chisinau' => '(GMT+2:00) Europe/Chisinau (Eastern European Time)',
		'Europe/Helsinki' => '(GMT+2:00) Europe/Helsinki (Eastern European Time)',
		'Europe/Istanbul' => '(GMT+2:00) Europe/Istanbul (Eastern European Time)',
		'Europe/Kaliningrad' => '(GMT+2:00) Europe/Kaliningrad (Eastern European Time)',
		'Europe/Kiev' => '(GMT+2:00) Europe/Kiev (Eastern European Time)',
		'Europe/Mariehamn' => '(GMT+2:00) Europe/Mariehamn (Eastern European Time)',
		'Europe/Minsk' => '(GMT+2:00) Europe/Minsk (Eastern European Time)',
		'Europe/Nicosia' => '(GMT+2:00) Europe/Nicosia (Eastern European Time)',
		'Europe/Riga' => '(GMT+2:00) Europe/Riga (Eastern European Time)',
		'Europe/Simferopol' => '(GMT+2:00) Europe/Simferopol (Eastern European Time)',
		'Europe/Sofia' => '(GMT+2:00) Europe/Sofia (Eastern European Time)',
		'Europe/Tallinn' => '(GMT+2:00) Europe/Tallinn (Eastern European Time)',
		'Europe/Tiraspol' => '(GMT+2:00) Europe/Tiraspol (Eastern European Time)',
		'Europe/Uzhgorod' => '(GMT+2:00) Europe/Uzhgorod (Eastern European Time)',
		'Europe/Vilnius' => '(GMT+2:00) Europe/Vilnius (Eastern European Time)',
		'Europe/Zaporozhye' => '(GMT+2:00) Europe/Zaporozhye (Eastern European Time)',
		'Africa/Addis_Ababa' => '(GMT+3:00) Africa/Addis_Ababa (Eastern African Time)',
		'Africa/Asmara' => '(GMT+3:00) Africa/Asmara (Eastern African Time)',
		'Africa/Asmera' => '(GMT+3:00) Africa/Asmera (Eastern African Time)',
		'Africa/Dar_es_Salaam' => '(GMT+3:00) Africa/Dar_es_Salaam (Eastern African Time)',
		'Africa/Djibouti' => '(GMT+3:00) Africa/Djibouti (Eastern African Time)',
		'Africa/Kampala' => '(GMT+3:00) Africa/Kampala (Eastern African Time)',
		'Africa/Khartoum' => '(GMT+3:00) Africa/Khartoum (Eastern African Time)',
		'Africa/Mogadishu' => '(GMT+3:00) Africa/Mogadishu (Eastern African Time)',
		'Africa/Nairobi' => '(GMT+3:00) Africa/Nairobi (Eastern African Time)',
		'Antarctica/Syowa' => '(GMT+3:00) Antarctica/Syowa (Syowa Time)',
		'Asia/Aden' => '(GMT+3:00) Asia/Aden (Arabia Standard Time)',
		'Asia/Baghdad' => '(GMT+3:00) Asia/Baghdad (Arabia Standard Time)',
		'Asia/Bahrain' => '(GMT+3:00) Asia/Bahrain (Arabia Standard Time)',
		'Asia/Kuwait' => '(GMT+3:00) Asia/Kuwait (Arabia Standard Time)',
		'Asia/Qatar' => '(GMT+3:00) Asia/Qatar (Arabia Standard Time)',
		'Europe/Moscow' => '(GMT+3:00) Europe/Moscow (Moscow Standard Time)',
		'Europe/Volgograd' => '(GMT+3:00) Europe/Volgograd (Volgograd Time)',
		'Indian/Antananarivo' => '(GMT+3:00) Indian/Antananarivo (Eastern African Time)',
		'Indian/Comoro' => '(GMT+3:00) Indian/Comoro (Eastern African Time)',
		'Indian/Mayotte' => '(GMT+3:00) Indian/Mayotte (Eastern African Time)',
		'Asia/Tehran' => '(GMT+3:30) Asia/Tehran (Iran Standard Time)',
		'Asia/Baku' => '(GMT+4:00) Asia/Baku (Azerbaijan Time)',
		'Asia/Dubai' => '(GMT+4:00) Asia/Dubai (Gulf Standard Time)',
		'Asia/Muscat' => '(GMT+4:00) Asia/Muscat (Gulf Standard Time)',
		'Asia/Tbilisi' => '(GMT+4:00) Asia/Tbilisi (Georgia Time)',
		'Asia/Yerevan' => '(GMT+4:00) Asia/Yerevan (Armenia Time)',
		'Europe/Samara' => '(GMT+4:00) Europe/Samara (Samara Time)',
		'Indian/Mahe' => '(GMT+4:00) Indian/Mahe (Seychelles Time)',
		'Indian/Mauritius' => '(GMT+4:00) Indian/Mauritius (Mauritius Time)',
		'Indian/Reunion' => '(GMT+4:00) Indian/Reunion (Reunion Time)',
		'Asia/Kabul' => '(GMT+4:30) Asia/Kabul (Afghanistan Time)',
		'Asia/Aqtau' => '(GMT+5:00) Asia/Aqtau (Aqtau Time)',
		'Asia/Aqtobe' => '(GMT+5:00) Asia/Aqtobe (Aqtobe Time)',
		'Asia/Ashgabat' => '(GMT+5:00) Asia/Ashgabat (Turkmenistan Time)',
		'Asia/Ashkhabad' => '(GMT+5:00) Asia/Ashkhabad (Turkmenistan Time)',
		'Asia/Dushanbe' => '(GMT+5:00) Asia/Dushanbe (Tajikistan Time)',
		'Asia/Karachi' => '(GMT+5:00) Asia/Karachi (Pakistan Time)',
		'Asia/Oral' => '(GMT+5:00) Asia/Oral (Oral Time)',
		'Asia/Samarkand' => '(GMT+5:00) Asia/Samarkand (Uzbekistan Time)',
		'Asia/Tashkent' => '(GMT+5:00) Asia/Tashkent (Uzbekistan Time)',
		'Asia/Yekaterinburg' => '(GMT+5:00) Asia/Yekaterinburg (Yekaterinburg Time)',
		'Indian/Kerguelen' => '(GMT+5:00) Indian/Kerguelen (French Southern & Antarctic Lands Time)',
		'Indian/Maldives' => '(GMT+5:00) Indian/Maldives (Maldives Time)',
		'Asia/Calcutta' => '(GMT+5:30) Asia/Calcutta (India Standard Time)',
		'Asia/Colombo' => '(GMT+5:30) Asia/Colombo (India Standard Time)',
		'Asia/Kolkata' => '(GMT+5:30) Asia/Kolkata (India Standard Time)',
		'Asia/Katmandu' => '(GMT+5:45) Asia/Katmandu (Nepal Time)',
		'Antarctica/Mawson' => '(GMT+6:00) Antarctica/Mawson (Mawson Time)',
		'Antarctica/Vostok' => '(GMT+6:00) Antarctica/Vostok (Vostok Time)',
		'Asia/Almaty' => '(GMT+6:00) Asia/Almaty (Alma-Ata Time)',
		'Asia/Bishkek' => '(GMT+6:00) Asia/Bishkek (Kirgizstan Time)',
		'Asia/Dacca' => '(GMT+6:00) Asia/Dacca (Bangladesh Time)',
		'Asia/Dhaka' => '(GMT+6:00) Asia/Dhaka (Bangladesh Time)',
		'Asia/Novosibirsk' => '(GMT+6:00) Asia/Novosibirsk (Novosibirsk Time)',
		'Asia/Omsk' => '(GMT+6:00) Asia/Omsk (Omsk Time)',
		'Asia/Qyzylorda' => '(GMT+6:00) Asia/Qyzylorda (Qyzylorda Time)',
		'Asia/Thimbu' => '(GMT+6:00) Asia/Thimbu (Bhutan Time)',
		'Asia/Thimphu' => '(GMT+6:00) Asia/Thimphu (Bhutan Time)',
		'Indian/Chagos' => '(GMT+6:00) Indian/Chagos (Indian Ocean Territory Time)',
		'Asia/Rangoon' => '(GMT+6:30) Asia/Rangoon (Myanmar Time)',
		'Indian/Cocos' => '(GMT+6:30) Indian/Cocos (Cocos Islands Time)',
		'Antarctica/Davis' => '(GMT+7:00) Antarctica/Davis (Davis Time)',
		'Asia/Bangkok' => '(GMT+7:00) Asia/Bangkok (Indochina Time)',
		'Asia/Ho_Chi_Minh' => '(GMT+7:00) Asia/Ho_Chi_Minh (Indochina Time)',
		'Asia/Hovd' => '(GMT+7:00) Asia/Hovd (Hovd Time)',
		'Asia/Jakarta' => '(GMT+7:00) Asia/Jakarta (West Indonesia Time)',
		'Asia/Krasnoyarsk' => '(GMT+7:00) Asia/Krasnoyarsk (Krasnoyarsk Time)',
		'Asia/Phnom_Penh' => '(GMT+7:00) Asia/Phnom_Penh (Indochina Time)',
		'Asia/Pontianak' => '(GMT+7:00) Asia/Pontianak (West Indonesia Time)',
		'Asia/Saigon' => '(GMT+7:00) Asia/Saigon (Indochina Time)',
		'Asia/Vientiane' => '(GMT+7:00) Asia/Vientiane (Indochina Time)',
		'Indian/Christmas' => '(GMT+7:00) Indian/Christmas (Christmas Island Time)',
		'Antarctica/Casey' => '(GMT+8:00) Antarctica/Casey (Western Standard Time (Australia))',
		'Asia/Brunei' => '(GMT+8:00) Asia/Brunei (Brunei Time)',
		'Asia/Choibalsan' => '(GMT+8:00) Asia/Choibalsan (Choibalsan Time)',
		'Asia/Chongqing' => '(GMT+8:00) Asia/Chongqing (China Standard Time)',
		'Asia/Chungking' => '(GMT+8:00) Asia/Chungking (China Standard Time)',
		'Asia/Harbin' => '(GMT+8:00) Asia/Harbin (China Standard Time)',
		'Asia/Hong_Kong' => '(GMT+8:00) Asia/Hong_Kong (Hong Kong Time)',
		'Asia/Irkutsk' => '(GMT+8:00) Asia/Irkutsk (Irkutsk Time)',
		'Asia/Kashgar' => '(GMT+8:00) Asia/Kashgar (China Standard Time)',
		'Asia/Kuala_Lumpur' => '(GMT+8:00) Asia/Kuala_Lumpur (Malaysia Time)',
		'Asia/Kuching' => '(GMT+8:00) Asia/Kuching (Malaysia Time)',
		'Asia/Macao' => '(GMT+8:00) Asia/Macao (China Standard Time)',
		'Asia/Macau' => '(GMT+8:00) Asia/Macau (China Standard Time)',
		'Asia/Makassar' => '(GMT+8:00) Asia/Makassar (Central Indonesia Time)',
		'Asia/Manila' => '(GMT+8:00) Asia/Manila (Philippines Time)',
		'Asia/Shanghai' => '(GMT+8:00) Asia/Shanghai (China Standard Time)',
		'Asia/Singapore' => '(GMT+8:00) Asia/Singapore (Singapore Time)',
		'Asia/Taipei' => '(GMT+8:00) Asia/Taipei (China Standard Time)',
		'Asia/Ujung_Pandang' => '(GMT+8:00) Asia/Ujung_Pandang (Central Indonesia Time)',
		'Asia/Ulaanbaatar' => '(GMT+8:00) Asia/Ulaanbaatar (Ulaanbaatar Time)',
		'Asia/Ulan_Bator' => '(GMT+8:00) Asia/Ulan_Bator (Ulaanbaatar Time)',
		'Asia/Urumqi' => '(GMT+8:00) Asia/Urumqi (China Standard Time)',
		'Australia/Perth' => '(GMT+8:00) Australia/Perth (Western Standard Time (Australia))',
		'Australia/West' => '(GMT+8:00) Australia/West (Western Standard Time (Australia))',
		'Australia/Eucla' => '(GMT+8:45) Australia/Eucla (Central Western Standard Time (Australia))',
		'Asia/Dili' => '(GMT+9:00) Asia/Dili (Timor-Leste Time)',
		'Asia/Jayapura' => '(GMT+9:00) Asia/Jayapura (East Indonesia Time)',
		'Asia/Pyongyang' => '(GMT+9:00) Asia/Pyongyang (Korea Standard Time)',
		'Asia/Seoul' => '(GMT+9:00) Asia/Seoul (Korea Standard Time)',
		'Asia/Tokyo' => '(GMT+9:00) Asia/Tokyo (Japan Standard Time)',
		'Asia/Yakutsk' => '(GMT+9:00) Asia/Yakutsk (Yakutsk Time)',
		'Australia/Adelaide' => '(GMT+9:30) Australia/Adelaide (Central Standard Time (South Australia))',
		'Australia/Broken_Hill' => '(GMT+9:30) Australia/Broken_Hill (Central Standard Time (South Australia/New South Wales))',
		'Australia/Darwin' => '(GMT+9:30) Australia/Darwin (Central Standard Time (Northern Territory))',
		'Australia/North' => '(GMT+9:30) Australia/North (Central Standard Time (Northern Territory))',
		'Australia/South' => '(GMT+9:30) Australia/South (Central Standard Time (South Australia))',
		'Australia/Yancowinna' => '(GMT+9:30) Australia/Yancowinna (Central Standard Time (South Australia/New South Wales))',
		'Antarctica/DumontDUrville' => '(GMT+10:00) Antarctica/DumontDUrville (Dumont-d\'Urville Time)',
		'Asia/Sakhalin' => '(GMT+10:00) Asia/Sakhalin (Sakhalin Time)',
		'Asia/Vladivostok' => '(GMT+10:00) Asia/Vladivostok (Vladivostok Time)',
		'Australia/ACT' => '(GMT+10:00) Australia/ACT (Eastern Standard Time (New South Wales))',
		'Australia/Brisbane' => '(GMT+10:00) Australia/Brisbane (Eastern Standard Time (Queensland))',
		'Australia/Canberra' => '(GMT+10:00) Australia/Canberra (Eastern Standard Time (New South Wales))',
		'Australia/Currie' => '(GMT+10:00) Australia/Currie (Eastern Standard Time (New South Wales))',
		'Australia/Hobart' => '(GMT+10:00) Australia/Hobart (Eastern Standard Time (Tasmania))',
		'Australia/Lindeman' => '(GMT+10:00) Australia/Lindeman (Eastern Standard Time (Queensland))',
		'Australia/Melbourne' => '(GMT+10:00) Australia/Melbourne (Eastern Standard Time (Victoria))',
		'Australia/NSW' => '(GMT+10:00) Australia/NSW (Eastern Standard Time (New South Wales))',
		'Australia/Queensland' => '(GMT+10:00) Australia/Queensland (Eastern Standard Time (Queensland))',
		'Australia/Sydney' => '(GMT+10:00) Australia/Sydney (Eastern Standard Time (New South Wales))',
		'Australia/Tasmania' => '(GMT+10:00) Australia/Tasmania (Eastern Standard Time (Tasmania))',
		'Australia/Victoria' => '(GMT+10:00) Australia/Victoria (Eastern Standard Time (Victoria))',
		'Australia/LHI' => '(GMT+10:30) Australia/LHI (Lord Howe Standard Time)',
		'Australia/Lord_Howe' => '(GMT+10:30) Australia/Lord_Howe (Lord Howe Standard Time)',
		'Asia/Magadan' => '(GMT+11:00) Asia/Magadan (Magadan Time)',
		'Antarctica/McMurdo' => '(GMT+12:00) Antarctica/McMurdo (New Zealand Standard Time)',
		'Antarctica/South_Pole' => '(GMT+12:00) Antarctica/South_Pole (New Zealand Standard Time)',
		'Asia/Anadyr' => '(GMT+12:00) Asia/Anadyr (Anadyr Time)',
		'Asia/Kamchatka' => '(GMT+12:00) Asia/Kamchatka (Petropavlovsk-Kamchatski Time)'
	);

	$fobrain_footer = '<span class=" fs-12">&copy<script>document.write(new Date().getFullYear())</script> 
		 					<b>'.$FoBrain.$fobrain_version.'</b><span class="col-i-4"></span></span>';

	$fobrain_footer_in = '<p class="mb-0 text-dark fs-12">
							&copy<script>document.write(new Date().getFullYear())</script> 
							<b> '.$FoBrain.$fobrain_version.' </b><span class="col-i-4"></span></p>';


?>